name: Run Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myapp
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install backend dependencies
        run: |
          cd laba4/backend
          npm install

      - name: Fix Jest permissions
        run: |
          cd laba4/backend
          chmod +x node_modules/.bin/*

      - name: Run backend tests
        run: |
          cd laba4/backend
          npm test
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test